### PR TITLE
Add calculate by days option for depreciation

### PR DESCRIPTION
**Pull request by kittiu**
@luc-demeyer 
I think best way is to add "Calculate by days" option, which apply to all types of method. WDYT?
@kittiu 
Agree.
Note: I will write test for it later.

### CODE REVIEW

**Comment by kittiu** [comment]
@luc-demeyer 
I think this pretty much it, on what I think we need. Any comments?

**Comment by kittiu** [comment]
@luc-demeyer it has be a while. Not sure what you plan to proceed on your PR, and I could help with anything?

**Comment by luc-demeyer** [comment]
I think it would be good if you also add a unit test on the days method.

**Comment by kittiu** [comment]
@luc-demeyer sorry for the delay, now it is quite ready.

**Comment by kittiu** [comment]
@luc-demeyer 
One notice, i.e., in account_asset.py, we are using standard python round() and not Odoo's float_round(). Is it recommended to use float_round() or there is no problem.

**Comment by luc-demeyer** [comment]
@kittiu 
A couple of remarks based after code reading:

1) account_asset.xml
I think we should hide the line_days field in the depreciation_table except for 'days_calc' assets (-> add invisible via attrs)

2) account_asset.py

line 788 - 791:
            if self.days_calc:
                line_dates.append(stop_date)
            else:
                line_dates.append(line_date)
This if-else clause should be not there. The line date for the last entry should be correctly calculated and such a calc is independent of days_calc true or false.

line 821-827
                if (line_date > min(entry['date_stop'],
                                    depreciation_stop_date) and not
                        (i == i_max and li == li_max)):
                    prev_date = line_date
                    break
                else:
                    prev_date = line_date + relativedelta(days=1)

imho this line block should be
                if (line_date > min(entry['date_stop'],
                                    depreciation_stop_date) and not
                        (i == i_max and li == li_max)):
                    break
                prev_date = line_date

lines 834 and 841:
                    if entry.get('day_amount') > 0.0:
This must be replaced by 
                    if entry.get('day_amount'):

Assets can also have NEGATIVE amounts !

line 872:
            if self.method_time == 'year' and not entry.get('day_amount'):
should remain:
            if self.method_time == 'year':

We should keep the FY based rounding correction as is.
If we calculate by days than there is a different amount between long (31 days and shorter months (<= 30 days) but at the end of the year the amount depreciated on an annual basis should be same independent of the choice to go for monthly, quarterly and annual depreciations.

line 842:
           amount = line_days * entry.get('day_amount')
should become
           amount = round(line_days * entry.get('day_amount'), digits)

line 981:
            day_amount = round(self.depreciation_base / days, digits)
should become
            day_amount = self.depreciation_base / days

We should not perform rounding on the day amount since the rounding differences at the end of the month and end of the year will become much too high.

**Comment by kittiu** [comment]
Already in PR to v12.

**Pull request closed without merging**
